### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by text2sql** [lablab-ai/whisper-gpt3-streamlit#1]
I am getting this error "[Errno 2] No such file or directory:" all packages seem to have installed just fine. Help please!

**Comment by chaoscreater** [comment]
Getting the same issue as well. 

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/e8ec41cf-f6f2-4b42-8eef-a1ca5b097e82)


Turns out that you need to manually create the downloads folder in your cloned repo locally.

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/60a282b3-fa93-41d7-b126-9247c4a18535)


And then it'll work. You can use the test MP3 files in the uploads folder. 

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/8db6bd44-6156-456e-b99d-e033c08b803e)


However, I'm now getting this new error related to Numpy, but it's already installed. It doesn't seem like this has been very well tested before release....

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/f9fb4e3a-211b-410b-a9ff-4f1be91232f9)

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/516f0f10-c366-41c4-a900-ec34c8f309d4)

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/17a6e664-ae21-476a-9a30-407a2d5e985f)

UPDATE:

Fixed it. Need to update Numpy to a newer version:
`
pip install numpy==1.24.1
`
source: https://stackoverflow.com/questions/71689095/how-to-solve-the-pytorch-runtimeerror-numpy-is-not-available-without-upgrading

![image](https://github.com/lablab-ai/whisper-gpt3-streamlit/assets/18227319/d1b34cd0-6949-43c8-82d6-190eb9d278ef)

Also, just be aware that when you upload the MP3 file, it'll cache it in this folder:
%UserProfile%\.cache\whisper

and depending on which model you use, the cache can grow very quickly, despite the file that you uploaded being tiny. It'll eat up your disk space.

**Comment by ezzcodeezzlife** [comment]
thanks @chaoscreater for highlighting this, i will pin it.
